Uploading & Downloading Benchmarking Data
NeuroDataDesign/brainlit pull request #20
Opened 2020-12-11 07:19 UTC by shreyasingh1

Created upload_benchmarking.py to automate scaling and upload of the 50 image benchmarking data and their associated swc files.  Made changes to swc.py to automate this process as well. Created uploading notebook called upload_benchmarking.ipynb. Upload destination is: s3://open-neurodata/brainlit/benchmarking_data.

Created download_benchmarking.ipynb tutorial to show (1) how to download the data from S3 using Neuroglancer and (2) how to locally download the data using the AWS CLI. To automate download, a few minor changes were made in session.py and swc.py in the form of optional parameters to existing functions. The downloading notebook can visualize any .tif file and its overlaid .swc's, either from S3 or from a local file location.

2020-12-11 19:07 UTC, tathey1 reviewed
The notebooks are beautiful.

My main question is why did you need to write a whole new upload_benchmarking.py? Why couldn't you have reused code from upload.py? Not saying it's not ok, but I want to know. Can @bvarjavand review upload_benchmarking.py and download_benchmarking.py and comment on whether its possible to combine with upload/py/download.py?

2020-12-11 19:07 UTC, tathey1 commented on brainlit/utils/session.py
>          ).astype(int)
You seem to redefine voxel immediately - isn't line 97 useless?

2020-12-11 19:07 UTC, tathey1 commented on brainlit/utils/session.py
> +            benchmark: Optional, default False. If True (relevant for benchmarking data), S3 file isn't rounded.
I'd like to avoid having a whole extra argument for just this dataset if possible. Is it possible to remove rounding from the original function? And then if there are other things that depend on the rounding just make those things round themselves?

2020-12-11 19:07 UTC, tathey1 commented on brainlit/utils/swc.py
> +def read_s3(s3_path, seg_id, mip, benchmark: Optional[bool] = False):
same comment as above - can you try to remove this argument?

2020-12-11 19:07 UTC, tathey1 commented on brainlit/utils/swc.py
> +
like earlier comment - if you remove this code will it break anything? worth looking into

2020-12-11 19:09 UTC, tathey1 requested changes
a few minor comments, and a discussion id like to have with Bijan

2020-12-11 19:27 UTC, bvarjavand commented
It seems like the main difference is the point at which you scale the data. I don't see any obvious reason why you couldn't merge this with upload.py (maybe you thought you shouldn't edit existing code? Then our bad, you have the go-ahead as long as tests pass).

2020-12-11 19:58 UTC, shreyasingh1 commented
@tathey1 The reason I kept upload_benchmarking.py separate is because I didn't want to break anything in upload.py, but I do now think that combining the scripts would make upload.py a bit heavy. 
Specifically:
- in get_volume_info I imported the benchmarking scaling information, calculated offset and used that to set the origin, and also modified the file path line and img_size line
- in create_cloud_volume I made the chunk size 1 instead of 4 and changed the scaling
- in get_data_ranges i modified the scale factor
- in upload_segments i added a line to divide vertices by the swc scaling factor
By contrast, in swc.py I only needed to make small changes so I just made a new function instead of making an entire swc_benchmarking.py. That being said, happy to try to combine them if you all think that's best.

In regards to the benchmarking parameter, I used it to just get around the rounding step in read_s3. When there's rounding, the benchmarking swc files load incorrectly (just as 0s and 1s) but without rounding they load correctly. Without rounding, the regular downloading_brains notebook also works. @bvarjavand do you know of anywhere else where rounding is necessary? If there isn't too many, I can remove the benchmarking parameter. If the rounding part is important though, is there a better way to get around it than an Optional benchmarking parameter?

2020-12-12 17:11 UTC, tathey1 commented
Regarding rounding, from my perspective (worth getting Bijan's also), as long as things don't break, nothing is inherently off limits.

Regarding the upload scripts, I think it's definitely worth trying to use the original create_cloud_volume and get_data_ranges functions, just add an argument to them for chunk size/scale factor and you should be good. If this is possible for get_volume_info also, I think it's worth it.

Do you think you can combine those files so there's only a single upload.py and no upload_benchmarking.py? Is there anything else besides using keyword arguments that you'd need to do to combine?

2020-12-12 22:26 UTC, shreyasingh1 commented
@tathey1 just merged upload_benchmarking.py into upload.py and both upload_brains.ipynb and upload_benchmarking.ipynb still run! I also changed the name of the benchmarking parameter to "rounding" to make it less specific to the benchmarking data, but can get rid of it all together as well.

2020-12-12 22:28 UTC, shreyasingh1 commented on brainlit/utils/session.py
>          ).astype(int)
Yep, thanks for catching that. Removed!

2020-12-13 22:51 UTC, tathey1 commented
@shreyasingh1 there are some merge conflicts with this PR, please merge your branch with deploy. Other than that, I think things look good.

2020-12-13 23:17 UTC, shreyasingh1 commented
@tathey1 sounds good, just addressed the merge conflicts!

2020-12-14 14:20 UTC, bvarjavand reviewed
Looks good. I currently don't see any output for your notebooks when I look at your branch. How do I know they run without issue?

2020-12-14 14:20 UTC, bvarjavand commented on brainlit/utils/swc.py
> +    benchmark: bool, Optional
change this to the correct parameter name

2020-12-14 14:20 UTC, bvarjavand commented on brainlit/utils/swc.py
> +def swc2skeleton_benchmarking(swc_file, origin=None):
it looks like the only difference between this method and `swc2skeleton` method is the way you get the ID and `origin` not being checked before subtraction. Seems reasonable to just update the existing method, why make a new one?

2020-12-14 14:20 UTC, bvarjavand commented on docs/notebooks/utils/downloading_brains.ipynb
> -}
you deleted the entire downloading_brains notebook? Is this necessary for your PR to pass?

2020-12-14 15:31 UTC, tathey1 commented
Then please open this PR into [here](https://github.com/neurodata/brainlit), and close this one

2020-12-14 19:32 UTC, closed without merging