WSL2 installation and configuration guide
NeuroDataDesign/brainlit pull request #4
Opened 2020-09-21 17:09 UTC by shreyasingh1

Added `WSL2-install-instructions.md` in `brainlit/docs` and linked to this file in `README.md`

2020-09-21 19:43 UTC, tathey1 requested changes
overall, great job

2020-09-21 19:43 UTC, tathey1 commented on README.md
> +Brainlit is compatible with iOS, Windows, and Unix systems.
Mac, not iOS.

2020-09-21 19:43 UTC, tathey1 commented on README.md
> +For Windows 10 users that prefer Linux functionality without the speed sacrifice of a VM, Brainlit can be installed and run on WSL2. See installation walkthrough [here.](docs/WSL2-install-instruction
"virtual machine" instead of "VM"

2020-09-21 20:27 UTC, shreyasingh1 commented
@tathey1 just updated, thanks!

2020-09-23 16:45 UTC, bvarjavand approved these changes
Great. Very thorough.

2020-09-23 17:42 UTC, bvarjavand commented
This behavior implies that you need to pull the most recent changes from `develop` into your branch.

2020-09-23 17:51 UTC, shreyasingh1 commented
@bvarjavand hm it says I'm up to date with develop and the upstream develop, and branch changes should be pushed. Is there anything else I can try changing?

2020-09-23 18:03 UTC, tathey1 approved these changes

2020-09-23 19:00 UTC, bvarjavand commented
see #12

2020-09-23 19:00 UTC, closed without merging